"""
helm/cloud/plan.py — What goes on the server: the compose file and its settings.

Two containers:
  rapr      — RAPR AI (headless). Not published to the internet.
  tunnel    — cloudflared "quick tunnel": a free https://<random>.trycloudflare.com
              address that reaches RAPR. No account and no domain needed. The
              address changes if the tunnel restarts; RAPR shows the new one.

Secrets: the PIN is stored only as a hash (computed here, on your computer).
The AI keys and chat-app tokens you choose to copy are written to the server's
.env with permission 600 and never leave your server.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

IMAGE = "ghcr.io/rawalrahul/raprai:latest"
TUNNEL_IMAGE = "cloudflare/cloudflared:latest"
DEFAULT_DIR = "/opt/rapr"

# Settings that may be copied to the server (AI keys and chat apps). Nothing else.
COPYABLE = (
    "GEMINI_API_KEY", "OPENAI_API_KEY", "OPENROUTER_API_KEY", "GROQ_API_KEY",
    "GITHUB_TOKEN", "ELEVENLABS_API_KEY", "LOCAL_AI_URL", "LOCAL_AI_MODEL",
    "TELEGRAM_BOT_TOKEN", "ALLOWED_USER_IDS",
    "DISCORD_BOT_TOKEN", "DISCORD_ALLOWED_USER_IDS",
    "SLACK_BOT_TOKEN", "SLACK_APP_TOKEN", "SLACK_ALLOWED_USER_IDS",
    "WHATSAPP_ALLOWED_NUMBERS", "KELVIN_DAILY_CHECKIN", "TELEGRAM_KELVIN_STICKERS",
)


@dataclass
class CloudOptions:
    host: str
    user: str = "ubuntu"
    port: int = 22
    name: str = "rapr"               # used in folder and container names
    pin_salt: str = ""
    pin_hash: str = ""
    copy_settings: list[str] = field(default_factory=list)
    local_env: dict = field(default_factory=dict)   # only COPYABLE keys are read from here


def validate(opts: CloudOptions) -> None:
    if not re.fullmatch(r"[A-Za-z0-9._-]{1,253}", opts.host or ""):
        raise ValueError("enter the server's IP address or host name")
    if not re.fullmatch(r"[a-z0-9-]{1,30}", opts.name or ""):
        raise ValueError("server name: lowercase letters, digits and dashes")
    if not re.fullmatch(r"[A-Za-z0-9._-]{1,64}", opts.user or ""):
        raise ValueError("SSH user name looks wrong")
    if not 1 <= int(opts.port) <= 65535:
        raise ValueError("SSH port must be between 1 and 65535")
    if not (opts.pin_salt and opts.pin_hash):
        raise ValueError("set a PIN first: the server must be locked")


def server_env(opts: CloudOptions) -> str:
    """The .env written on the server (no secrets beyond the chosen ones)."""
    lines = [
        "# Written by RAPR AI cloud setup. Keep this file private (chmod 600).",
        "RAPR_HEADLESS=1",
        "RAPR_DATA_DIR=/data",
        f"PIN_SALT={opts.pin_salt}",
        f"PIN_HASH={opts.pin_hash}",
    ]
    for key in opts.copy_settings:
        if key in COPYABLE and opts.local_env.get(key):
            value = str(opts.local_env[key]).replace("\n", " ")
            lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def compose_file(opts: CloudOptions) -> str:
    """docker-compose.yml for the server."""
    return f"""# RAPR AI on your server. Generated by RAPR AI cloud setup.
name: {opts.name}
services:
  rapr:
    image: {IMAGE}
    restart: unless-stopped
    env_file: .env
    volumes:
      - rapr-data:/data
      # The app reads and writes /data/.env (setup, PIN, settings); this is the
      # same file, so changes made in the server's Settings are kept on the server.
      - ./.env:/data/.env
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  tunnel:
    image: {TUNNEL_IMAGE}
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://rapr:8000
    depends_on:
      - rapr

volumes:
  rapr-data:
"""


TUNNEL_URL = re.compile(r"https://[a-z0-9-]+\.trycloudflare\.com")
